# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-17 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
